
-- Copyright (c) 2003, 2008-2012, Oracle and/or its affiliates. All rights reserved.
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; version 2 of the License.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

-- DO NOT EDIT THIS FILE. It is generated automatically.

-- To use this file, load its contents into the mysql database. For example,
-- with the mysql client program, process the file like this, where
-- file_name is the name of this file:

--     mysql -u root -p mysql < file_name

set names 'utf8';

set sql_log_bin = 0;

use mysql;
delete from help_topic;
delete from help_category;
delete from help_keyword;
delete from help_relation;

lock tables help_topic write, help_category write, help_keyword write, help_relation write;
insert into help_category (help_category_id,name,parent_category_id,url) values (1,'Contents',0,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (2,'Polygon Properties',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (3,'WKT',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (4,'Numeric Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (5,'Plugins',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (6,'MBR',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (7,'Control Flow Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (8,'Transactions',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (9,'Help Metadata',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (10,'Account Management',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (11,'Point Properties',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (12,'Encryption Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (13,'LineString Properties',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (14,'Miscellaneous Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (15,'Logical Operators',47,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (16,'Functions and Modifiers for Use with GROUP BY',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (17,'Information Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (18,'Assignment Operators',47,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (19,'Comparison Operators',47,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (20,'Bit Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (21,'Table Maintenance',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (22,'User-Defined Functions',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (23,'Data Types',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (24,'Compound Statements',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (25,'Geometry Constructors',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (26,'Administration',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (27,'Data Manipulation',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (28,'Utility',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (29,'Language Structure',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (30,'Geometry Relations',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (31,'Date and Time Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (32,'WKB',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (33,'Procedures',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (34,'Geographic Features',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (35,'Geometry Properties',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (36,'String Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (37,'Functions',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (38,'Data Definition',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (39,'Sequences',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (40,'JSON Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (41,'Window Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (42,'Spider Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (43,'Dynamic Column Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (44,'Galera Functions',37,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (45,'Temporal Tables',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (46,'GeoJSON',34,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (47,'Operators',1,'');
insert into help_category (help_category_id,name,parent_category_id,url) values (48,'Arithmetic Operators',47,'');

insert into help_topic (help_topic_id,help_category_id,name,description,example,url) values (1,9,'HELP_DATE','Help Contents generated from the MariaDB Knowledge Base on 09 September 2022.','','');


unlock tables;